### ISSUE TITLE
suspicous DOIs found in BatLit v0.7

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#45]
After running 

we found the following 

```
cat bin/doi-status.tsv | grep -v 302 | grep -v 301
```

```
404	https://doi.org/10.19136/era.a8nI.2656
404	https://doi.org/10.1644/09-MAMM-A-325.1.Key
404	https://doi.org/10.1002/path
404	https://doi.org/10.1371/journal.
000	pone.0200303
404	https://doi.org/10.1128/mBio.00164-10.Editor
404	https://doi.org/10.3201/eid1706.101355
404	https://doi.org/10.1007/s13398-014-0173-7.2
404	https://doi.org/10.1172/32108.of
404	https://doi.org/10.1002/pbc
404	https://doi.org/10.3724/SP.J.1141.2010.06633
404	https://doi.org/10.4404/hystrix–00063-2018
```

@ajacsherman please review these suspicious DOIs - they originate from the Zotero group that you curate at https://www.zotero.org/groups/5435545/bat_literature_project .

**Comment by jhpoelen** [comment]
Please let me know how you are doing these searches. 

Here's what I found:


```
García-Morales,2021,"Lista actualizada de los murciélagos de la Reserva de la Biosfera Pantanos de Centla, cuencas Grijalva-Usumacinta.",Ecosist. Recur. Agropec.,journalArticle,1,e2656,,10.19136/era.a8nI.2656,https://www.zotero.org/groups/bat_literature_project/items/IP4DC48A,https://api.zotero.org/groups/5435545/items/AMZCUSWB,hash://md5/a08b59b55871df386b62db120d5b2abc,hash://md5/ce1e7618f237ff56e74d51f496e811a3
Sandoval | Szumik | Barquez,2010,Bats and marsupials as indicators of endemism in the Yungas forest of Argentina.,Zoological Research,journalArticle,31,6,633-644,10.3724/SP.J.1141.2010.06633,https://www.zotero.org/groups/bat_literature_project/items/DGIF58L4,https://api.zotero.org/groups/5435545/items/D3R6CWXX,hash://md5/eeba842a07efc532f6a6513d25fd6197,hash://md5/ce1e7618f237ff56e74d51f496e811a3
Roehrs | Lack | Van Den Bussche,2010,Tribal phylogenetic relationships within Vespertilioninae ( Chiroptera : Vespertilionidae ) based on mitochondrial and nuclear sequence data Tribal phylogenetic relationships within Vespertilioninae ( Chiroptera : Vespertilionidae ) based on mitochondrial,Journal of Mammalogy,journalArticle,91,5,1073-1092,10.1644/09-MAMM-A-325.1.Key,https://www.zotero.org/groups/bat_literature_project/items/LL5T2AXJ,https://api.zotero.org/groups/5435545/items/DUE9FUWS,hash://md5/4a09c8e387255562f83d982f6b42c16e,hash://md5/ce1e7618f237ff56e74d51f496e811a3
Fraser | Parker | Nakagawa | Fidler | Barnett,2018,Questionable Research Practices ( QRPs ) in Ecology and Evolution,PLoS ONE,journalArticle,13,7,e0200303,10.1371/journal. pone.0200303,https://www.zotero.org/groups/bat_literature_project/items/TE5RIWRU,https://api.zotero.org/groups/5435545/items/LK855N24,hash://md5/888ea95e5c0a1fd3be32d14ec2462876,hash://md5/ce1e7618f237ff56e74d51f496e811a3
Dragu | Csorba | Bancila,2019,Ecological character displacement in mandibular morphology of three sympatric horseshoe bats,"Hystrix, the Italian Journal of Mammalogy",journalArticle,30,1,51–58,10.4404/hystrix–00063-2018,https://www.zotero.org/groups/bat_literature_project/items/WQ6YQ52H,https://api.zotero.org/groups/5435545/items/NSQYX7Y2,hash://md5/4d2b412d3df070b65ac4661f2ec3a493,hash://md5/ce1e7618f237ff56e74d51f496e811a3
De Wit | Munster,01/2015,Animal models of disease shed light on Nipah virus pathogenesis and transmission,The Journal of Pathology,journalArticle,235,2,196-205,10.1002/path.4444,https://www.zotero.org/groups/bat_literature_project/items/ML6PYEXB,https://api.zotero.org/groups/5435545/items/WIYMEZ96,hash://md5/f86d3440e5f18fdd472b451fa1bd3da5,hash://md5/ce1e7618f237ff56e74d51f496e811a3
```

**Comment by ajacsherman** [comment]
Good morning,
Thanks for these! I'm searching Zotero for the DOIs since that's the only
clue I have from our report. They don't show up that way. I don't know why.
I'm reporting these to DOI.org.

García-Morales,2021 has a corrupt DOI everywhere.
https://era.ujat.mx/index.php/rera/article/view/2656
Sandoval | Szumik | Barquez,2010 is also corrupt everywhere.
https://ri.conicet.gov.ar/handle/11336/72430
Roehrs | Lack | Van Den Bussche,2010 is correct. 10.1644/09-MAMM-A-325.1
Fraser | Parker | Nakagawa | Fidler | Barnett,2018.  I deleted this since
it does not contain any reference to bats.
Dragu | Csorba | Bancila,2019.  Fixed.
https://doi.org/10.4404/hystrix-00120-2018
 De Wit | Munster,01/2015 This one worked? https://doi.org/10.1002/path.4444

Talk soon,
Aja




On Fri, Dec 13, 2024 at 12:50 PM Jorrit Poelen ***@***.***>
wrote:
>
> Please let me know how you are doing these searches.
>
> Here's what I found:
>
> García-Morales,2021,"Lista actualizada de los murciélagos de la Reserva
de la Biosfera Pantanos de Centla, cuencas Grijalva-Usumacinta.",Ecosist.
Recur. Agropec.,journalArticle,1,e2656,,10.19136/era.a8nI.2656,
https://www.zotero.org/groups/bat_literature_project/items/IP4DC48A,https://api.zotero.org/groups/5435545/items/AMZCUSWB,hash://md5/a08b59b55871df386b62db120d5b2abc,hash://md5/ce1e7618f237ff56e74d51f496e811a3
> Sandoval | Szumik | Barquez,2010,Bats and marsupials as indicators of
endemism in the Yungas forest of Argentina.,Zoological
Research,journalArticle,31,6,633-644,10.3724/SP.J.1141.2010.06633,
https://www.zotero.org/groups/bat_literature_project/items/DGIF58L4,https://api.zotero.org/groups/5435545/items/D3R6CWXX,hash://md5/eeba842a07efc532f6a6513d25fd6197,hash://md5/ce1e7618f237ff56e74d51f496e811a3
> Roehrs | Lack | Van Den Bussche,2010,Tribal phylogenetic relationships
within Vespertilioninae ( Chiroptera : Vespertilionidae ) based on
mitochondrial and nuclear sequence data Tribal phylogenetic relationships
within Vespertilioninae ( Chiroptera : Vespertilionidae ) based on
mitochondrial,Journal of
Mammalogy,journalArticle,91,5,1073-1092,10.1644/09-MAMM-A-325.1.Key,
https://www.zotero.org/groups/bat_literature_project/items/LL5T2AXJ,https://api.zotero.org/groups/5435545/items/DUE9FUWS,hash://md5/4a09c8e387255562f83d982f6b42c16e,hash://md5/ce1e7618f237ff56e74d51f496e811a3
> Fraser | Parker | Nakagawa | Fidler | Barnett,2018,Questionable Research
Practices ( QRPs ) in Ecology and Evolution,PLoS
ONE,journalArticle,13,7,e0200303,10.1371/journal. pone.0200303,
https://www.zotero.org/groups/bat_literature_project/items/TE5RIWRU,https://api.zotero.org/groups/5435545/items/LK855N24,hash://md5/888ea95e5c0a1fd3be32d14ec2462876,hash://md5/ce1e7618f237ff56e74d51f496e811a3
> Dragu | Csorba | Bancila,2019,Ecological character displacement in
mandibular morphology of three sympatric horseshoe bats,"Hystrix, the
Italian Journal of
Mammalogy",journalArticle,30,1,51–58,10.4404/hystrix–00063-2018,
https://www.zotero.org/groups/bat_literature_project/items/WQ6YQ52H,https://api.zotero.org/groups/5435545/items/NSQYX7Y2,hash://md5/4d2b412d3df070b65ac4661f2ec3a493,hash://md5/ce1e7618f237ff56e74d51f496e811a3
> De Wit | Munster,01/2015,Animal models of disease shed light on Nipah
virus pathogenesis and transmission,The Journal of
Pathology,journalArticle,235,2,196-205,10.1002/path.4444,
https://www.zotero.org/groups/bat_literature_project/items/ML6PYEXB,https://api.zotero.org/groups/5435545/items/WIYMEZ96,hash://md5/f86d3440e5f18fdd472b451fa1bd3da5,hash://md5/ce1e7618f237ff56e74d51f496e811a3
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
***@***.***>



--
Aja Sherman MS
Bat Eco-Interactions Database Curator
Associate in Mammalogy, American Museum of Natural History
https://batbase.org/
914-886-8906
***@***.***
***@***.***
***@***.***
she/her

**Comment by jhpoelen** [comment]
discussed with @ajacsherman , closing issue.
